### ISSUE TITLE
Foundry Server Debug Log shows warning...

### ISSUE THREAD

**Issue by karpana** [David-Zvekic/pushTokenBack#2]
When I restart my Foundry instance, this message is continually present in the `debug.log` file.

Foundry Version: v9 build 249
System: PF1
Host/Server Operating System: Raspberry Pi 4.

```
{"level":"warn","message":"Package pushTokenBack contains 1 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2022-02-07 09:18:04"}
```

**Comment by David-Zvekic** [comment]
this module is no longer being maintained. I suggest using Your Tokens
Visible which has this feature and many others.

**Comment by karpana** [comment]
Thanks for the update David-Zvekic.

I'll look to switch over to the other module you've suggested.
